all:
	gcc -O2 -fmessage-length=0 -std=c99 -Wall -Wextra -Wwrite-strings -Winit-self -Wcast-align -Wcast-qual -Wpointer-arith -Wstrict-aliasing -Wformat=2 -Wmissing-include-dirs -Wno-unused-parameter -Wshadow -Wuninitialized -Wold-style-definition triangle.c -o triangle -lm

clean:
	rm -f triangle
