#!/bin/bash

#out of range test
echo "1. expected: error, actual: " 
./triangle 0 0 0 0 0 1073741824
echo "2. expected: error, actual: "
./triangle 0 0 0 0 0 -1073741824
#too few arguments
echo "3. expected: error, actual: "
./triangle 0 0 0 0 0 

#too many arguments
echo "4. expected: error, actual: "
./triangle 0 0 0 0 0 0 0

#colinear points
echo "5. expected: not a triangle, actual: "
./triangle 0 0 1073741823 1073741823 -1073741823 -1073741823

#not a triangle
echo "6. expected: not a triangle, actual: "
./triangle 1 1 1 1 1 1

#Triangles
echo "7. expected: scalene acute, actual: "
./triangle 0 0 0 10 9 9

echo "8. expected: scalene obtuse, actual: "
./triangle 0 0 0 10 9 100

echo "9. expected: scalene right, actual: "
./triangle 0 0 0 2 4 0

echo "10. expected: isosceles right, actual: "
./triangle 0 0 0 2 2 0

echo "11. expected: isosceles acute, actual: "
./triangle 0 0 1 2 2 0

echo "12. expected: isosceles obtuse, actual: "
./triangle 0 0 10 2 20 0
